version: "3"

services:
  nats:
    container_name: nats
    image: nats
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'

  postgres:
    container_name: postgres
    image: postgres:14-bullseye
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=dev
